//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 產生Excel報表 的當地語系化字串。
        /// </summary>
        internal static string ButtonMakeExcelReport {
            get {
                return ResourceManager.GetString("ButtonMakeExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳檔案 的當地語系化字串。
        /// </summary>
        internal static string Button_Choice_Files {
            get {
                return ResourceManager.GetString("Button_Choice_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳圖片 的當地語系化字串。
        /// </summary>
        internal static string Button_Choice_Images {
            get {
                return ResourceManager.GetString("Button_Choice_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string Button_Modify {
            get {
                return ResourceManager.GetString("Button_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        internal static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回前頁 的當地語系化字串。
        /// </summary>
        internal static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始上傳檔案 的當地語系化字串。
        /// </summary>
        internal static string Button_Start_FilesUp {
            get {
                return ResourceManager.GetString("Button_Start_FilesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始上傳圖片 的當地語系化字串。
        /// </summary>
        internal static string Button_Start_ImagesUp {
            get {
                return ResourceManager.GetString("Button_Start_ImagesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure {
            get {
                return ResourceManager.GetString("Button_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Insert {
            get {
                return ResourceManager.GetString("Button_Sure_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定修改 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Modify {
            get {
                return ResourceManager.GetString("Button_Sure_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string ColModify {
            get {
                return ResourceManager.GetString("ColModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Single Malt 的當地語系化字串。
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NT$ 的當地語系化字串。
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email已驗證等待審核通過 的當地語系化字串。
        /// </summary>
        internal static string C_MemberState_EmailPass {
            get {
                return ResourceManager.GetString("C_MemberState_EmailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新加入Email驗證中 的當地語系化字串。
        /// </summary>
        internal static string C_MemberState_New {
            get {
                return ResourceManager.GetString("C_MemberState_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常 的當地語系化字串。
        /// </summary>
        internal static string C_MemberState_Normal {
            get {
                return ResourceManager.GetString("C_MemberState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停權中 的當地語系化字串。
        /// </summary>
        internal static string C_MemberState_Stop {
            get {
                return ResourceManager.GetString("C_MemberState_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正常 的當地語系化字串。
        /// </summary>
        internal static string C_UserState_Normal {
            get {
                return ResourceManager.GetString("C_UserState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 暫停 的當地語系化字串。
        /// </summary>
        internal static string C_UserState_Pause {
            get {
                return ResourceManager.GetString("C_UserState_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 除權 的當地語系化字串。
        /// </summary>
        internal static string C_UserState_Stop {
            get {
                return ResourceManager.GetString("C_UserState_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料刪除完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Delete_Success {
            get {
                return ResourceManager.GetString("Data_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料新增完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Insert_Success {
            get {
                return ResourceManager.GetString("Data_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料異動完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Trans_Success {
            get {
                return ResourceManager.GetString("Data_Trans_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料更新完成 的當地語系化字串。
        /// </summary>
        internal static string Data_Update_Success {
            get {
                return ResourceManager.GetString("Data_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除資料! 的當地語系化字串。
        /// </summary>
        internal static string Info_Delete_Data {
            get {
                return ResourceManager.GetString("Info_Delete_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案列表(IE10、Chrome、Mozilla Firefox及Opera可選多檔上傳) 的當地語系化字串。
        /// </summary>
        internal static string Info_Files_List {
            get {
                return ResourceManager.GetString("Info_Files_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案上傳 的當地語系化字串。
        /// </summary>
        internal static string Info_FileUploader {
            get {
                return ResourceManager.GetString("Info_FileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本期核銷完成。 的當地語系化字串。
        /// </summary>
        internal static string Info_FinishVerify {
            get {
                return ResourceManager.GetString("Info_FinishVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片列表(IE10、Chrome、Mozilla Firefox及Opera可選多張圖片上傳) 的當地語系化字串。
        /// </summary>
        internal static string Info_Images_List {
            get {
                return ResourceManager.GetString("Info_Images_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登錄資訊 的當地語系化字串。
        /// </summary>
        internal static string Info_LoginInfo {
            get {
                return ResourceManager.GetString("Info_LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無資料可列印。 的當地語系化字串。
        /// </summary>
        internal static string Info_NoDataToPrint {
            get {
                return ResourceManager.GetString("Info_NoDataToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數字愈大愈前面 的當地語系化字串。
        /// </summary>
        internal static string Info_Sort_Memo {
            get {
                return ResourceManager.GetString("Info_Sort_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊為必填欄位 的當地語系化字串。
        /// </summary>
        internal static string Info_StarMustEdit {
            get {
                return ResourceManager.GetString("Info_StarMustEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統提醒 的當地語系化字串。
        /// </summary>
        internal static string Info_SystemAlert {
            get {
                return ResourceManager.GetString("Info_SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案上傳協助器 的當地語系化字串。
        /// </summary>
        internal static string Info_Title_FileUpload {
            get {
                return ResourceManager.GetString("Info_Title_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片上傳協助器 的當地語系化字串。
        /// </summary>
        internal static string Info_Title_ImageUpload {
            get {
                return ResourceManager.GetString("Info_Title_ImageUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行訊息 的當地語系化字串。
        /// </summary>
        internal static string Info_WorkResult {
            get {
                return ResourceManager.GetString("Info_WorkResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除？ 的當地語系化字串。
        /// </summary>
        internal static string IsSureDelete {
            get {
                return ResourceManager.GetString("IsSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!狀態不符。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Normal {
            get {
                return ResourceManager.GetString("Login_Err_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!請重輸入帳號或密碼。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Password {
            get {
                return ResourceManager.GetString("Login_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已存在，不可使用。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_AccountExists {
            get {
                return ResourceManager.GetString("Log_Err_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此檔案類型不在充許範圍。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_AllowFileType {
            get {
                return ResourceManager.GetString("Log_Err_AllowFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案數量超過限制。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_FileCountOver {
            get {
                return ResourceManager.GetString("Log_Err_FileCountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案容量超過限制。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_FileSizeOver {
            get {
                return ResourceManager.GetString("Log_Err_FileSizeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此節仍其下仍有資料，需先刪除其下節點才能刪除此節點。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_HasSubTreeData {
            get {
                return ResourceManager.GetString("Log_Err_HasSubTreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入的驗證碼不正確，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_ImgValideNotEquel {
            get {
                return ResourceManager.GetString("Log_Err_ImgValideNotEquel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該檔案類型禁止上傳。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_LimitedFileType {
            get {
                return ResourceManager.GetString("Log_Err_LimitedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤，無任何資料傳出。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_MustHaveData {
            get {
                return ResourceManager.GetString("Log_Err_MustHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼和新密碼不一致，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordNotSure {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordNotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼和舊密碼不可相同。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordSame {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該日期無設定任何產品資料。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NoSetDate {
            get {
                return ResourceManager.GetString("Log_Err_NoSetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品編號已存在。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_OrderSerialExists {
            get {
                return ResourceManager.GetString("Log_Err_OrderSerialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單序號不正確。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_OrderSerialIsNull {
            get {
                return ResourceManager.GetString("Log_Err_OrderSerialIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發生益繳狀況，核銷失敗。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_OverFlower {
            get {
                return ResourceManager.GetString("Log_Err_OverFlower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不正確，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Password {
            get {
                return ResourceManager.GetString("Log_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印報表需輸入正確查詢條件。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_PrintCondition {
            get {
                return ResourceManager.GetString("Log_Err_PrintCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該產品序號已存在。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_ProdSerialExists {
            get {
                return ResourceManager.GetString("Log_Err_ProdSerialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ***系統提醒*** 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Title {
            get {
                return ResourceManager.GetString("Log_Err_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此客戶為第一次繳費無前期資料 的當地語系化字串。
        /// </summary>
        internal static string Log_Info_FirstPayData {
            get {
                return ResourceManager.GetString("Log_Info_FirstPayData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string NoMessage {
            get {
                return ResourceManager.GetString("NoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢無任何資料。 的當地語系化字串。
        /// </summary>
        internal static string Search_No_Data {
            get {
                return ResourceManager.GetString("Search_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇要刪除的列。 的當地語系化字串。
        /// </summary>
        internal static string Select_Delete_Data {
            get {
                return ResourceManager.GetString("Select_Delete_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料庫Table訂義模組未定義此欄位。 的當地語系化字串。
        /// </summary>
        internal static string Sys_Err_FieldNotExists {
            get {
                return ResourceManager.GetString("Sys_Err_FieldNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Sys_Err_Title {
            get {
                return ResourceManager.GetString("Sys_Err_Title", resourceCulture);
            }
        }
    }
}
