//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18408
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWeb() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 崧賀營造有限公司,兆辰土木包工業 的當地語系化字串。
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ¥ 的當地語系化字串。
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 连接服务器发生错误，请联络管理员。 的當地語系化字串。
        /// </summary>
        internal static string Err_ConnectionServerOut {
            get {
                return ResourceManager.GetString("Err_ConnectionServerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email格式不正确 的當地語系化字串。
        /// </summary>
        internal static string Err_Field_Email_Format {
            get {
                return ResourceManager.GetString("Err_Field_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此栏需填写 的當地語系化字串。
        /// </summary>
        internal static string Err_Field_Require {
            get {
                return ResourceManager.GetString("Err_Field_Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 账号已处于登录状态无法完成 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginState {
            get {
                return ResourceManager.GetString("Err_LoginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失败，请重新输Email及密码。 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginUnCorrect {
            get {
                return ResourceManager.GetString("Err_LoginUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 请先登录以完成该项作业 的當地語系化字串。
        /// </summary>
        internal static string Err_LogoutState {
            get {
                return ResourceManager.GetString("Err_LogoutState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 电子邮件已存在。 的當地語系化字串。
        /// </summary>
        internal static string Err_MailHasExist {
            get {
                return ResourceManager.GetString("Err_MailHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 邮件账号不存在。 的當地語系化字串。
        /// </summary>
        internal static string Err_MailNotExist {
            get {
                return ResourceManager.GetString("Err_MailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 验证无效 的當地語系化字串。
        /// </summary>
        internal static string Err_MembernNoValidCode {
            get {
                return ResourceManager.GetString("Err_MembernNoValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该会员状态无法登录 的當地語系化字串。
        /// </summary>
        internal static string Err_MemberStateNotAllowLogin {
            get {
                return ResourceManager.GetString("Err_MemberStateNotAllowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该会员状态已无法验证，或已验证完成。 的當地語系化字串。
        /// </summary>
        internal static string Err_MemberValidState {
            get {
                return ResourceManager.GetString("Err_MemberValidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 确认密码不符 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordConfirm {
            get {
                return ResourceManager.GetString("Err_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码长度不符(至少6个字符) 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordLength {
            get {
                return ResourceManager.GetString("Err_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码不正确 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordNotCorrect {
            get {
                return ResourceManager.GetString("Err_PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码规则不符(需包含英、数字) 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordRule {
            get {
                return ResourceManager.GetString("Err_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该笔订单已支付过 的當地語系化字串。
        /// </summary>
        internal static string Err_PayHasFinished {
            get {
                return ResourceManager.GetString("Err_PayHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各密码字段不可以有空白 的當地語系化字串。
        /// </summary>
        internal static string Err_pwdHasBlank {
            get {
                return ResourceManager.GetString("Err_pwdHasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此字段需填写。 的當地語系化字串。
        /// </summary>
        internal static string Err_RequireData {
            get {
                return ResourceManager.GetString("Err_RequireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Session已遗失。 的當地語系化字串。
        /// </summary>
        internal static string Err_SessionLost {
            get {
                return ResourceManager.GetString("Err_SessionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 验证码不正确 的當地語系化字串。
        /// </summary>
        internal static string Err_ValideUnCorrect {
            get {
                return ResourceManager.GetString("Err_ValideUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 产品加入购物车完成。 的當地語系化字串。
        /// </summary>
        internal static string Info_AddCartItemOK {
            get {
                return ResourceManager.GetString("Info_AddCartItemOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 数量更改完成。 的當地語系化字串。
        /// </summary>
        internal static string Info_AmtChangeFinish {
            get {
                return ResourceManager.GetString("Info_AmtChangeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 该项产品删除完成。 的當地語系化字串。
        /// </summary>
        internal static string Info_ItemRemoveFinish {
            get {
                return ResourceManager.GetString("Info_ItemRemoveFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 会员数据更新完成。 的當地語系化字串。
        /// </summary>
        internal static string Info_MemberDataModifyOK {
            get {
                return ResourceManager.GetString("Info_MemberDataModifyOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 注册会员完成，请至Email信箱收取验证信件，以启动账号。(若找不到系统来信时请看有无被移至垃圾信箱) 的當地語系化字串。
        /// </summary>
        internal static string Info_MemberRegistStep1 {
            get {
                return ResourceManager.GetString("Info_MemberRegistStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未购买任何项目。 的當地語系化字串。
        /// </summary>
        internal static string Info_NoShoppingItem {
            get {
                return ResourceManager.GetString("Info_NoShoppingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码更更改完成，下次登录请用新密码登录。 的當地語系化字串。
        /// </summary>
        internal static string Info_PasswordDataModifyOK {
            get {
                return ResourceManager.GetString("Info_PasswordDataModifyOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码已寄出，请至您的信箱收取。 的當地語系化字串。
        /// </summary>
        internal static string Info_PWDResend {
            get {
                return ResourceManager.GetString("Info_PWDResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码须包括英数及六个字元以上 的當地語系化字串。
        /// </summary>
        internal static string Info_PWD_Principle {
            get {
                return ResourceManager.GetString("Info_PWD_Principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Single Malt&lt;info@jcin.com.tw&gt; 的當地語系化字串。
        /// </summary>
        internal static string MailAdmin {
            get {
                return ResourceManager.GetString("MailAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 感谢您加入Single Malt会员 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectAddMember {
            get {
                return ResourceManager.GetString("MailSubjectAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Single Malt【订单信息】-测试中 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectOrderInfo {
            get {
                return ResourceManager.GetString("MailSubjectOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Single Malt B2B 密码重寄通知 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectPWDReSend {
            get {
                return ResourceManager.GetString("MailSubjectPWDReSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码重设通知 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectRestPWD {
            get {
                return ResourceManager.GetString("MailSubjectRestPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://www.whisky898.com 的當地語系化字串。
        /// </summary>
        internal static string PublicUrl {
            get {
                return ResourceManager.GetString("PublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 崧賀營造有限公司,兆辰土木包工業,桃園建築工程,桃園土木工程,桃園廠房工程,桃園廠房新建,桃園廠房改建,桃園鋼構工程 的當地語系化字串。
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
